version: "3.8"

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/dbs
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identitydb
    user: root
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=my_s@cret_p@ssw!ord
  orderdb:
    container_name: orderdb
    user: root
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=my_s@cret_p@ssw!ord
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - RabbitMQUrl=rabbitmq
      - IdentityServerUrl=http://identityserver.api:5001
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - catalogdb
  identityserver.api:
    container_name: identityserver.api
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433; Database=IdentityDb; User Id=SA; Password=my_s@cret_p@ssw!ord"
    ports:
      - "5001:80"
    depends_on:
      - identitydb
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - IdentityServerUrl=http://identityserver.api:5001
      - RedisSettings:Port=6379
      - RedisSettings:Host=basketdb
    ports:
      - "5013:80"
    depends_on:
      - basketdb
  photostock.api:
    container_name: photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - IdentityServerUrl=http://identityserver.api:5001
    ports:
      - "5012:80"
    volumes:
      - type: bind
        source: /Users/alibulut/Personal/Workspace/ASP.NETCore/MicroservicesProjectPhotos
        target: /app/wwwroot/photos
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - IdentityServerUrl=http://identityserver.api:5001
      - "ConnectionStrings:PostgreSQL=User ID=admin; Password=admin; Server=discountdb; Port=5432; Database=discountdb;"
    ports:
      - "5014:80"
    depends_on:
      - discountdb
  fakepayment.api:
    container_name: fakepayment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - RabbitMQUrl=rabbitmq
      - IdentityServerUrl=http://identityserver.api:5001
    ports:
      - "5016:80"
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - RabbitMQUrl=rabbitmq
      - IdentityServerUrl=http://identityserver.api:5001
      - "ConnectionStrings:DefaultConnection=Server=orderdb,1444; Database=OrderDb; User Id=SA; Password=my_s@cret_p@ssw!ord"
    ports:
      - "5015:80"
    depends_on:
      - orderdb
